image_root: 'data/ICFG-PEDES/imgs'
train_file: ['data/ICFG-PEDES/processed_data/train.json']
val_file: 'data/ICFG-PEDES/processed_data/test.json'

test_file: 'data/ICFG-PEDES/processed_data/test.json'


use_cross_aug: False

## Vision Encoder
use_beit_v2: True
vision_config: 'configs/config_beit2_base.json'
image_res: 384
patch_size: 16
embed_dim: 256
use_mask: False

use_momentum: True
momentum: 0.995

temp: 0.07

## Text Encoder (& Cross Encoder)
text_encoder: 'configs/bert-base-uncased'
text_tokenizer: 'bert-base-uncased'

text_num_hidden_layers: 18
text_fusion_start_at: 12

## Training
num_dec_layers: 6
large_lr_for_dec: True
batch_size_train: 32
accumulate_steps: 1
batch_size_test_text: 256
batch_size_test: 256
max_tokens: 40
k_test: 128

use_sdm: False
use_id_loss: False

num_classes: 11003

# MLM
mlm: True
max_words: 30
mask_prob: 0.5
max_masks: 12
mask_whole_word: True
skipgram_prb: 0.2
skipgram_size: 3

erasing_p: 0.6

## Other Settings
optimizer: {opt: adamW, lr: 1e-5, weight_decay: 0.01, lr_mult: 2, vision_lr: 1e-5, text_lr: 1e-5}
schedular: {sched: cosine, epochs: 61, num_warmup_steps: 0.1}
eval_epoch: 3  # epoch index

use_cnn_feats: False
cnn_net: regnety_016
